### ISSUE TITLE
GHA might need an update with respect to dplyr

### ISSUE THREAD

**Issue by pat-s** [trendecon/data#24] opened 2021-01-20 07:01 UTC
Looks like a true-positive issue: https://github.com/trendecon/data/runs/1732490576?check_suite_focus=true#step:20:23389

@angelicambg Do you have time to take a look? Or maybe someone else who wrote this code?

Maybe @christophsax knows?

**Comment by christophsax** [comment] 2021-01-20 10:23
@karoliskoncevicius, can you look into it?

**Comment by karoliskoncevicius** [comment] 2021-01-20 10:56
@christophsax will look into it in a few hours.

**Comment by karoliskoncevicius** [comment] 2021-01-20 13:56
Seems like the error is coming from `proc_index.R`:

    # check if they have the same span
    nrow(distinct(ts_summary(data), start, end)) == 1 is not TRUE

So for some reason there was a mismatch with dates. Trying to see now if I can reproduce it. If not, it might just be a one-time download issue.

**Comment by karoliskoncevicius** [comment] 2021-01-20 14:15
OK - no error for me.

What seems to have happened:

1. Google had newer date for some keywords, but not others.
2. Because of that our update script ended up with different end dates for different keywords within the same index
3. This caused the script to fail, because it expects all keywords within the index to have the same span of dates.

**Comment by karoliskoncevicius** [comment] 2021-01-20 14:18
@christophsax I have two proposals:

1. Do nothing, as this will likely be fixed with the next update (seems like a rare occurance)
2. If we see discrepancy in dates (i.e. Mango last date is 01-16, but H&M is 01-15) - then we trim all series to the smallest end date (so we would remove all Mango dates above 01-15).

What do you think?

**Comment by christophsax** [comment] 2021-01-20 15:05
Try 1. first, if it persists, do 2.

**Comment by pat-s** [comment] 2021-01-22 10:12
@karoliskoncevicius GHA fails now for 3 days in a row, seems like we need to find a fix/workaround.

**Comment by karoliskoncevicius** [comment] 2021-01-22 15:52
@pat-s looking at it now.

This is a bit weird, as I don't get the same error locally, so cannot be 100% sure about the fix. By any chance - did the hour the tic update takes place change? My guess is that for some reason it starts the update at the same time google keywords are being updated, and so it starts to download keyword before the google update takes place, but in the middle google gets updated and so tic action obtains new data for other keywords in the process.

**Comment by karoliskoncevicius** [comment] 2021-01-22 17:59
@christophsax - this is getting a bit weird. Everything works on my machine, nut not with tic actions. And I see that for some keywords trendecon decided that the data is up to date and so doesn't update it, and for other keywords within the same index updates do happen, which leads to date mismatch.

I suggest to change the logic for checking dates. Proposal: compare the maximum local date with the date obtained from google (maybe by downloading the latest once). And if they are the same - skip the update step, otherwise run the update. What do you think?

**Comment by pat-s** [comment] 2021-01-22 18:00
No it did not change but you are free to change the time to see if it has an effect 🙂

**Comment by karoliskoncevicius** [comment] 2021-01-23 10:40
@christophsax @pat-s I temporarily removed the google_latest_date check in trendecon and will see if this fixes the issue.

**Comment by karoliskoncevicius** [comment] 2021-01-23 14:56
Added the adjustment of dates in case of mismatch: https://github.com/trendecon/trendecon/commit/710bfb9dab214abf80d2feb05c435779a18dfdee

Also, not sure why, but the latest dates from google seem to be 01-16 now.

**Comment by pat-s** [comment] 2021-01-23 16:59
Thanks @karoliskoncevicius!

**Comment by christophsax** [comment] 2021-02-05 18:10
So, this is resolved? Thanks!

**Closed as completed by christophsax** 2021-02-05 18:10 UTC
Labels: bug
